blogTitle = "Drunken Coder"
blogUrl = "http://blog.jetboystudio.com"
subTitle = "code like a drunken master"
authorName = "David Konsumer"
authorBio = "Written by <strong>David Konsumer</strong> who lives and works in Portland and makes rad stuff. You should follow him on <a href='https://twitter.com/davidkonsumer'>Twitter</a> &amp; <a href='https://github.com/konsumer'>Github</a>"
linkPrefix = ""
# disqusShortname = "jetboystudio"
gaCode = "UA-2392079-5"
kommentsCode = "e8620496-711c-4199-a7f5-8a64e47da13d"